"use client";

import { useActionState, useState } from "react";
import { useFormStatus } from "react-dom";
import Link from "next/link";
import { motion } from "motion/react";
import { ArrowLeft, ArrowRight, CheckCircle2, FileCheck2, LoaderCircle, LockKeyhole, Upload } from "lucide-react";
import { submitPublicApplication, type PublicApplicationState } from "@/app/(marketing)/careers/actions";
import { RESUME_FILE_ACCEPT } from "@/lib/recruitment/resume-files";

const initialState: PublicApplicationState = { status: "idle", message: "" };
const inputClass = "h-12 w-full rounded-xl border border-line bg-white px-4 text-sm outline-none transition placeholder:text-muted/50 focus:border-blue-500 focus:ring-4 focus:ring-blue-100";
const labelClass = "mb-2 block text-sm font-bold text-ink";

export function PublicApplicationForm({ jobId, organizationId, jobTitle }: { jobId: string; organizationId: string; jobTitle: string }) {
  const [state, action] = useActionState(submitPublicApplication, initialState);
  if (state.status === "success") {
    return <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="rounded-3xl border border-blue-100 bg-white p-8 text-center shadow-[0_24px_70px_rgba(37,99,235,.1)] sm:p-12"><span className="mx-auto grid size-16 place-items-center rounded-full bg-blue-50 text-blue-700"><CheckCircle2 size={30} /></span><p className="mt-7 font-mono text-xs uppercase tracking-[.1em] text-blue-700">Application received</p><h1 className="mt-3 text-3xl font-bold tracking-[-.045em]">Thank you for applying.</h1><p className="mx-auto mt-4 max-w-md text-sm leading-7 text-muted">{state.message} The hiring team will review your job-related experience and contact you if your profile moves forward.</p>{state.reference && <div className="mx-auto mt-7 max-w-sm rounded-xl border border-blue-100 bg-blue-50 p-4"><p className="text-xs uppercase text-muted">Application reference</p><p className="mt-2 font-mono text-sm font-bold text-blue-800">{state.reference}</p></div>}<Link href="/careers" className="mt-8 inline-flex h-11 items-center gap-2 rounded-xl border border-line px-5 text-sm font-bold transition hover:border-blue-200 hover:bg-blue-50"><ArrowLeft size={14} /> Back to careers</Link></motion.div>;
  }

  return <form action={action} className="overflow-hidden rounded-3xl border border-line bg-white shadow-[0_24px_70px_rgba(25,72,133,.08)]"><input type="hidden" name="jobId" value={jobId} /><input type="hidden" name="organizationId" value={organizationId} /><input className="absolute -left-[9999px]" type="text" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" /><div className="border-b border-line bg-gradient-to-r from-blue-50 to-white p-6 sm:p-8"><p className="font-mono text-xs uppercase tracking-[.1em] text-blue-700">Candidate application</p><h1 className="mt-3 text-2xl font-bold tracking-[-.04em]">Apply for {jobTitle}</h1><p className="mt-2 text-sm leading-6 text-muted">Fields marked with an asterisk are required.</p></div><div className="grid gap-6 p-6 sm:grid-cols-2 sm:p-8"><Field required label="Full name *" name="fullName" autoComplete="name" /><Field required label="Email address *" name="email" type="email" autoComplete="email" /><Field label="Phone" name="phone" type="tel" autoComplete="tel" /><Field label="Current location" name="location" autoComplete="address-level2" /><Field required label="Years of relevant experience *" name="yearsExperience" type="number" min="0" max="60" step="0.5" defaultValue="0" /><Select label="Highest education *" name="educationLevel" options={["any", "high_school", "associate", "bachelor", "master", "doctorate"]} /><Field label="Relevant skills · comma separated" name="declaredSkills" placeholder="Inventory, procurement, forecasting" className="sm:col-span-2" /><ResumeFileInput /><TextArea required label="Resume text *" name="resumeText" placeholder="Paste the text from your resume so the hiring team can review job-relevant experience." /><TextArea label="Cover letter" name="coverLetter" placeholder="Tell us why this role is a good match for your experience." /><label className="sm:col-span-2 flex items-start gap-3 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm leading-5 text-blue-900"><input required type="checkbox" name="consent" className="mt-1 size-4 shrink-0 accent-blue-600" /><span>I consent to the secure storage and review of this application. I understand job-related resume content may be processed by an assisted ranking tool, with final decisions made by the hiring team.</span></label>{state.status === "error" && <p role="alert" className="sm:col-span-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{state.message}</p>}</div><div className="flex flex-col-reverse items-center justify-between gap-4 border-t border-line bg-[#f8faff] p-6 sm:flex-row sm:px-8"><span className="inline-flex items-center gap-2 text-xs text-muted"><LockKeyhole size={12} /> Your application is private and access-controlled.</span><SubmitApplicationButton /></div></form>;
}

function ResumeFileInput() {
  const [fileName, setFileName] = useState("");
  return <label className="sm:col-span-2"><span className={labelClass}>Resume file · optional</span><span className="flex min-h-24 cursor-pointer items-center justify-center gap-3 rounded-xl border border-dashed border-blue-200 bg-blue-50/60 px-4 text-sm text-blue-700 transition hover:bg-blue-50">{fileName ? <FileCheck2 size={18} /> : <Upload size={17} />}<span className="min-w-0 truncate">{fileName || "Upload PDF, DOCX, or TXT · maximum 10 MB"}</span><input className="sr-only" type="file" name="resumeFile" accept={RESUME_FILE_ACCEPT} onChange={(event) => setFileName(event.currentTarget.files?.[0]?.name ?? "")} /></span></label>;
}
function Field({ label, className, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className={className}><span className={labelClass}>{label}</span><input className={inputClass} {...props} /></label>; }
function TextArea({ label, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement> & { label: string }) { return <label className="sm:col-span-2"><span className={labelClass}>{label}</span><textarea className="min-h-36 w-full resize-y rounded-xl border border-line bg-white p-4 text-sm leading-6 outline-none transition placeholder:text-muted/50 focus:border-blue-500 focus:ring-4 focus:ring-blue-100" {...props} /></label>; }
function Select({ label, name, options }: { label: string; name: string; options: string[] }) { return <label><span className={labelClass}>{label}</span><select required name={name} defaultValue="" className={inputClass}><option value="" disabled>Select one</option>{options.map((option) => <option key={option} value={option}>{humanize(option)}</option>)}</select></label>; }
function SubmitApplicationButton() { const { pending } = useFormStatus(); return <button disabled={pending} className="inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-accent px-6 text-sm font-bold text-white shadow-[0_12px_30px_rgba(37,99,235,.22)] transition hover:-translate-y-0.5 hover:bg-blue-700 disabled:translate-y-0 disabled:cursor-wait disabled:opacity-65 sm:w-auto">{pending ? <><LoaderCircle className="animate-spin" size={16} /> Submitting…</> : <>Submit application <ArrowRight size={15} /></>}</button>; }
function humanize(value: string) { return value.replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase()); }
